# Generated by Django 4.2.7 on 2023-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='Sex')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('hobby', models.CharField(max_length=50, verbose_name='Hobby')),
                ('like_food', models.CharField(max_length=50, verbose_name='Like food')),
                ('like_music', models.CharField(max_length=50, verbose_name='Like music')),
                ('like_book', models.CharField(max_length=50, verbose_name='Like book')),
                ('like_game', models.CharField(max_length=50, verbose_name='Like game')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
            ],
        ),
    ]
